name: Release ytui-music v2.0.0-beta

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE.txt'
      - 'screenshots/'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Install dependencies
        run: |
              git submodule init
              sudo apt update &&
              sudo apt install libmpv2 libmpv-dev

      - name: Build
        run: |
              cargo build --all --release &&
              strip target/release/ytui_music &&
              mv target/release/ytui_music target/release/ytui_music-linux-amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{  github.ref_name }}
          files: |
            target/release/ytui_music-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

